---
- name: innodb-replicaset-mysql-install | Check if mysqld is running
  shell: pgrep -a "^mysqld$"
  ignore_errors: True
  changed_when: False
  register: mysql_proc_status
  
- name: innodb-replicaset-mysql-install | Check if Mysql Server already installed
  stat: path=/usr/sbin/mysqld
  register: mysql_bin

- name: innodb-replicaset-mysql-install | Begin install Percona Server
  block:
    - name: Clean APT cache
      apt:
        update_cache: yes
        autoclean: yes
        autoremove: yes
    
    - name: Install MySQL APT config package
      apt:
        deb: https://repo.mysql.com/mysql-apt-config_0.8.32-1_all.deb
        state: present
    
    - name: Configure MySQL APT repository
      debconf:
        name: mysql-apt-config
        question: mysql-apt-config/select-server
        value: mysql-8.0
        vtype: select
    
    - name: Ensure package cache is updated
      apt:
        update_cache: yes

    - name: innodb-replicaset-mysql-install | Install InnoDB tools and dependency packages
      apt:
        pkg:
          - mysql-server
          - mysql-client
          - mysql-router
          - mysql-shell
          - python3-mysqldb
          - libmysqlclient21
          - libmysqlclient-dev
        state: present

    - name: Ensure MySQL is running
      service:
        name: mysql
        state: started
        enabled: yes

    - name: innodb-replicaset-mysql-install | Prepare log path
      file:
        path: /var/log/mysql
        state: directory
        owner: mysql
        group: mysql
        mode: 0755

  when: mysql_bin.stat.exists == False and mysql_proc_status.rc != 0

- name: innodb-replicaset-mysql-install | Add Mysql Server logrotate
  copy:
    src: mysql_server.logrotate.conf
    dest: /etc/logrotate.d/mysql
    owner: root
    group: root
    mode: 0644
  tags:
    - update_logrorate_config

- name: innodb-replicaset-mysql-install | Create a directory for the systemd service modification
  file:
    path: '/usr/lib/systemd/system/mysql.service.d'
    state: directory
    owner: root
    group: root
    mode: 0755

- name: innodb-replicaset-mysql-install | Update mysqld systemd resource limit
  template:
    src: systemd/custom.conf.j2
    dest: '/usr/lib/systemd/system/mysql.service.d/custom.conf'
    owner: root
    group: root
    mode: 0644
  with_dict: '{{ systemd_services }}'
  notify: systemd reload
  tags:
    - update_mysqld_systemd_resource_limit

- name: innodb-replicaset-mysql-install | Install mysqlshell-plugins
  ansible.builtin.git:
    repo: https://github.com/lefred/mysqlshell-plugins.git
    dest: /root/.mysqlsh/plugins
    version: master
    update: no

- name: innodb-replicaset-mysql-install | Install mysqlsh request module
  shell: >
    mysqlsh --pym pip install requests
  register: mysqlsh_install_module_result
  changed_when: "'Successfully installed' in mysqlsh_install_module_result.stdout"
  failed_when: "'ERROR' in mysqlsh_install_module_result.stderr"
