---
- name: innodb-replicaset-create-change-data-capture-users | Create CDC users
  mysql_user:
    login_unix_socket: "{{ percona_server_configuration.my_cnf.socket | default('/var/run/mysqld/mysqld.sock') }}"
    name: "{{ item.name }}"
    password: "{{ item.password | default('p@ssW0rd') }}"
    encrypted: "{{ item.encrypted | default('no') }}"
    priv: "{{ item.priv | default('test.*:ALL') }}"
    state: "{{ item.state | default('present') }}"
    host: "{{ item.host | default('localhost') }}"
  no_log: True
  with_items: "{{ percona_server_change_data_capture_users }}"